freebsd_instance:
  image_family: freebsd-13-0

task:
  install_script:
  - pkg install -y poudriere
  create_env_script:
  - poudriere jail -c -j 13amd64 -v 13.0-RELEASE
  - poudriere ports -c -p local
  - cd /usr/local/poudriere/ports/local
  - fetch https://github.com/glebius/ports/commit/678212c679d7d442d852ab19f248b0006cf7ecfd.patch
  - patch -p1 < 678212c679d7d442d852ab19f248b0006cf7ecfd.patch
  - poudriere bulk -j 13amd64 -p local net-im/tg_owt
